
// Auto-generated by fix script.
// Reads API URL from Vite environment
export const API = import.meta.env.VITE_API_URL || 'http://localhost:8088';
export const WS_URL = import.meta.env.VITE_WS_URL || 'ws://localhost:8088/ws';
